### ISSUE TITLE
진행할 프로젝트 선택에 대한 논의

### ISSUE THREAD

**Issue by Joseph-Cha** [Joseph-Cha/ProjectDiscussion#1]
2가지 안으로 작성했습니다.

웹 사이트 / 2D MMORPG

선택에 앞서 아래 2가지 관점을 가장 중점적으로 생각하고 있습니다.

1. 기본
2. 시간 절약

시작이 많이 늦었기 때문에 시행착오를 최대한 줄이고 싶고 그만큼 빠르게 성장하고 싶은 간절함이 있습니다.
모두 장단점이 있지만 개인적인 선택은 2D MMORPG를 시작하고 싶습니다.

비록 제가 처음부터 끝까지 부딪혀가면서 스스로 만든다는 경험은 부족할 수 있으나
그만큼 시간은 절약할 수 있으며 단순히 시키는 대로 만드는 것에 그치는 것이 아니라
**스스로 확장 구현**을 하는 것까지 고려해서 작업을 진행해볼까 합니다.
(물론 이렇게 하기 위해서 콘텐츠에 대한 기획을 좀더 생각해볼 필요가 있을 것 같습니다.)

**Comment by jongfeel** [comment]
기본적인걸 한다는 입장이라면 저는 좋습니다. 기본 적인 걸 잘 이해하고 익힌다면 나머지는 부수적이라고 할 수 있을 정도로 좋은 작전일 수도 있습니다.

시간 절약은 좋은 결과를 가져올 수도 아닐 수도 있습니다. 보통 시간 절약 작전은 쉽게 실패합니다. 왜 그러냐 하면 계획과 범위를 잡지 않고 시간 절약만 생각한다면 그렇기 때문입니다.

어쨌든 2D MMORPG로 시작하려고 하시는 건 좋은데 범위와 계획을 더 잘 세워야 합니다.
신입이 할 수 있는 부분이라면 아주 간단하고 단순한 범위만 목표로 해야 합니다.
MMO가 아니라 2인 네트워크 플레이로 범위를 좁혀도 원하는 기한내에 혹은 목표한 기능을 구현하지도 못할 수 있으니까요.

What에 대한 대략적인게 정해진 것 같으면
이제 기획을 잘 해보면 좋습니다.

**Comment by jongfeel** [comment]
Next

새로 진행할 게임 클라이언트의 repository 생성 후 진행
기획, 시나리오, 범위 등을 잘 선정해서 문서로 작성해 보기

총 기간, 주당 투자 시간, 시간 별 마일스톤 ( 예)50시간에 기획+설계 하기 등) 정해보기
자주 논의가 필요할 경우 한번에 몰아서 하지 말고 필요한대로 진행하기 => github discussion을 이용하면 좋습니다.

issue => 개발 진행시 생기는 문제점, 변경 사항, 버그 트래킹 등
discussion => (개발이 아닌) 일반적인 수준에서의 논의, 질문-답변

**Comment by Joseph-Cha** [comment]
p{margin-top:0;margin-bottom:0}
    


    우선 클라이언트 깃허브 개설하고 대략적인 기획안을 작성하고 있습니다 (https://github.com/Joseph-Cha/JustFight_Client)

말씀하신 discussion 기능은 어떻게 활용하는지 오늘 잠깐 시간날 때 알려주시면 감사하겠습니다😊

--------- 원본 메일 ---------

    
        보낸사람: Kim Jong Feel <notifications@github.com>
        받는사람: Joseph-Cha/ProjectDiscussion <ProjectDiscussion@noreply.github.com>
        
            참조: Joseph.c <joseph.c@kakao.com>, Assign <assign@noreply.github.com>
        
        날짜: 21.01.25 23:30 GMT +0900
        제목: Re: [Joseph-Cha/ProjectDiscussion] 진행할 프로젝트 선택에 대한 논의 (#1)
        
        
    
    
        
Next
새로 진행할 게임 클라이언트의 repository 생성 후 진행
기획, 시나리오, 범위 등을 잘 선정해서 문서로 작성해 보기
총 기간, 주당 투자 시간, 시간 별 마일스톤 ( 예)50시간에 기획+설계 하기 등) 정해보기
자주 논의가 필요할 경우 한번에 몰아서 하지 말고 필요한대로 진행하기 => github discussion을 이용하면 좋습니다.
issue => 개발 진행시 생기는 문제점, 변경 사항, 버그 트래킹 등
discussion => (개발이 아닌) 일반적인 수준에서의 논의, 질문-답변

**Comment by jongfeel** [comment]
https://github.com/Joseph-Cha/JustFight_Client/issues/1#issue-795226297

제가 위 링크에 적었습니다.
